name: build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Restore Gradle cache
      uses: actions/cache@v2
      env:
        cache-name: gradle-cache
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-build-${{ env.cache-name }}

    - name: Set up Gradle script
      run: chmod +rwx ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease --parallel --build-cache
